kind: Service
apiVersion: v1
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name:  backend
  labels:
    app: backend
spec:
  selector:
    app:  backend
  ports:
  - port:  3000
    targetPort:  3000
