apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: mohamedabdallah0/node-sqlite-app:latest
        ports:
        - containerPort: 3000
        env:
        - name: MONGODB_URI
          value: mongodb://mongodb:27017/myapp